"""initial schema: business_unit, department, employee, app_user, departure_event

Revision ID: d1049acb7f8f
Revises: 
Create Date: 2026-09-18 09:47:37.576906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd1049acb7f8f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_unit_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['business_unit_id'], ['business_unit.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_unit_id', 'name', name='uq_department_bu_name')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('date_of_joining', sa.Date(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('business_unit_id', sa.Integer(), nullable=False),
    sa.Column('designation', sa.String(length=120), nullable=True),
    sa.Column('grade', sa.String(length=2), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('ctc_annual', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('last_increment_date', sa.Date(), nullable=True),
    sa.Column('last_increment_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('last_promotion_date', sa.Date(), nullable=True),
    sa.Column('performance_rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('engagement_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('manager_effectiveness_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('employment_status', sa.String(length=10), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("employment_status IN ('active','separated')", name='ck_employee_status'),
    sa.CheckConstraint("gender IN ('Male','Female','Other') OR gender IS NULL", name='ck_employee_gender'),
    sa.CheckConstraint("grade IN ('L1','L2','L3','L4','L5','L6')", name='ck_employee_grade'),
    sa.CheckConstraint('performance_rating IS NULL OR (performance_rating BETWEEN 1 AND 5)', name='ck_employee_performance_rating'),
    sa.ForeignKeyConstraint(['business_unit_id'], ['business_unit.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('employee_code')
    )
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('business_unit_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("(role = 'hr' AND business_unit_id IS NULL) OR (role = 'bu_head' AND business_unit_id IS NOT NULL)", name='ck_app_user_bu_scope'),
    sa.CheckConstraint("role IN ('hr','bu_head')", name='ck_app_user_role'),
    sa.ForeignKeyConstraint(['business_unit_id'], ['business_unit.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('departure_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('business_unit_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('last_working_day', sa.Date(), nullable=True),
    sa.Column('departure_type', sa.String(length=15), nullable=False),
    sa.Column('reason_category', sa.String(length=50), nullable=True),
    sa.Column('reason_notes', sa.Text(), nullable=True),
    sa.Column('is_regretted', sa.Boolean(), nullable=True),
    sa.Column('notice_period_days', sa.Integer(), nullable=True),
    sa.Column('recorded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("departure_type IN ('voluntary','involuntary','retirement','other')", name='ck_departure_event_type'),
    sa.ForeignKeyConstraint(['business_unit_id'], ['business_unit.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('departure_event')
    op.drop_table('app_user')
    op.drop_table('employee')
    op.drop_table('department')
    op.drop_table('business_unit')
    # ### end Alembic commands ###
