"""add synthetic_employee table for Module 3 demo dataset

Revision ID: d8957d78dfd1
Revises: 5c6bf1a73a67
Create Date: 2026-09-21 14:02:52.434111

Same RLS/trigger/grant pattern as migration 5c6bf1a73a67 applied to
`employee` — see that migration's comments and MODULE3_REFERENCE.md's
"Dataset shape and where it lives" section for why this synthetic,
demo-only table still carries real RLS.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd8957d78dfd1'
down_revision: Union[str, None] = '5c6bf1a73a67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('synthetic_employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('date_of_joining', sa.Date(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('business_unit_id', sa.Integer(), nullable=False),
    sa.Column('designation', sa.String(length=120), nullable=True),
    sa.Column('grade', sa.String(length=2), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('ctc_annual', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('last_increment_date', sa.Date(), nullable=True),
    sa.Column('last_promotion_date', sa.Date(), nullable=True),
    sa.Column('performance_rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('engagement_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('manager_effectiveness_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('overtime', sa.Boolean(), nullable=False),
    sa.Column('job_satisfaction_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('distance_from_home_km', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('employment_status', sa.String(length=10), nullable=False),
    sa.Column('predicted_probability', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('risk_band', sa.String(length=10), nullable=True),
    sa.Column('shap_drivers', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("employment_status IN ('active','separated')", name='ck_synthetic_employee_status'),
    sa.CheckConstraint("gender IN ('Male','Female','Other') OR gender IS NULL", name='ck_synthetic_employee_gender'),
    sa.CheckConstraint("grade IN ('L1','L2','L3','L4','L5','L6')", name='ck_synthetic_employee_grade'),
    sa.CheckConstraint("risk_band IS NULL OR risk_band IN ('low','medium','high','critical')", name='ck_synthetic_employee_risk_band'),
    sa.ForeignKeyConstraint(['business_unit_id'], ['business_unit.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_code')
    )
    # ### end Alembic commands ###

    # --- Trigger: keep business_unit_id in sync with department_id --------
    op.execute(
        """
        CREATE OR REPLACE FUNCTION sync_synthetic_employee_business_unit() RETURNS trigger AS $$
        BEGIN
            NEW.business_unit_id := (
                SELECT business_unit_id FROM department WHERE id = NEW.department_id
            );
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_synthetic_employee_sync_business_unit
        BEFORE INSERT OR UPDATE OF department_id ON synthetic_employee
        FOR EACH ROW
        EXECUTE FUNCTION sync_synthetic_employee_business_unit();
        """
    )

    # --- Row Level Security — identical shape to employee's policies ------
    op.execute("ALTER TABLE synthetic_employee ENABLE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY synthetic_employee_hr_full_access ON synthetic_employee
        FOR ALL
        USING (current_setting('app.current_role', true) = 'hr')
        WITH CHECK (current_setting('app.current_role', true) = 'hr')
        """
    )
    op.execute(
        """
        CREATE POLICY synthetic_employee_bu_head_scoped ON synthetic_employee
        FOR ALL
        USING (
            current_setting('app.current_role', true) = 'bu_head'
            AND business_unit_id::text = current_setting('app.current_bu_id', true)
        )
        WITH CHECK (
            current_setting('app.current_role', true) = 'bu_head'
            AND business_unit_id::text = current_setting('app.current_bu_id', true)
        )
        """
    )

    # --- Runtime role grant -------------------------------------------------
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON synthetic_employee TO fri_app")


def downgrade() -> None:
    op.execute("REVOKE ALL ON synthetic_employee FROM fri_app")

    op.execute("DROP POLICY IF EXISTS synthetic_employee_bu_head_scoped ON synthetic_employee")
    op.execute("DROP POLICY IF EXISTS synthetic_employee_hr_full_access ON synthetic_employee")
    op.execute("ALTER TABLE synthetic_employee DISABLE ROW LEVEL SECURITY")

    op.execute("DROP TRIGGER IF EXISTS trg_synthetic_employee_sync_business_unit ON synthetic_employee")
    op.execute("DROP FUNCTION IF EXISTS sync_synthetic_employee_business_unit")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('synthetic_employee')
    # ### end Alembic commands ###
